

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  receiver-service:
    build:
      context: .
      dockerfile: apps/receiver-service/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    working_dir: /app/apps/receiver-service
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_URI: mongodb://mongodb:27017/pubmicroservice
    depends_on:
      - redis
      - mongodb
    command: npm run start:dev:receiver

  listener-service:
    build:
      context: .
      dockerfile: apps/listener-service/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app/apps/listener-service
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_URI: mongodb://mongodb:27017/pubmicroservice
    depends_on:
      - redis
      - mongodb
    command: npm run start:dev:listener

volumes:
  mongo_data:
